// CoffeeLake (C) 2026-*
// 
// The PortableExecutableRomFlower.cs represents extension of Microsoft PE object format 
// to dump Windows CE/Mobile firmware.
//
// PE ROM image could be generated by LINK.EXE/ROMIMAGE.EXE from Windows CE 2x SDK.
// (doesn't load into RAM, executes from flash storage directly)
// 
// Based sections: .text, .DATA, .kdata (NK.LIB/EXE details), .rsrc.
// Same with default Windows NT PEs, .rsrc section is a special section name
// (must be set and not renamed if image has embedded resources)
//
// @local_machine: atvlg
// @creator: atolstopyatov2017@vk.com

using SunFlower.Abstractions;
using SunFlower.Pe.Headers;

namespace SunFlower.Pe;

[FlowerVersionContract(5, 0, 0)]
[Flower(FlowerTarget.Data)]
public class PortableExecutableRomFlower : IFlower
{
    [Seed(
        name: "Portable Executable Header",
        description: "COFF header or file header is a mandatory structure in all `PE` modules\r\n" +
                     "The File Header is a structure that holds some information about the PE file."
    )]
    public PeFileHeader FileHeader { get; set; }
    
    [Seed(
        name: "Portable Executable Optional Header",
        description: "The Optional ROM header was applied to execute-in-place firmware,\r\n" +
                     "The modern versions of Microsoft Link can't emit ROM binaries, they were emitted by `ROMIMAGE.EXE`.\r\n" +
                     "_(see Windows CE 2x SDK)_. ROMs were used in Windows CE/Mobile, not for UEFI applications."
    )]
    public PeOptionalHeaderRom OptionalHeader { get; set; }
    
    [Seed(
        name: "Section Table",
        description: "Sections are the containers of the actual data of the executable file,\r\n " +
                     "they occupy the rest of the PE file after the headers, " +
                     "precisely after the section headers."
    )]
    public PeSection[] Sections { get; set; } = [];
    
    
    public Task CreateAsync(string filePath)
    {
        return Task.FromException(new NotImplementedException());
    }

    public string Name => "Portable Executable ROM Dump";
}